### ISSUE TITLE
Version 11.0.0.1458 not working at all.

### ISSUE THREAD

**Issue by N3tFX** [ONLYOFFICE/Docker-CommunityServer#106]
I tried the newer version of Community Server docker (11.0.0.1458) and it doesn't even start the services. It complains that the system is not a "**systemd** "system.

If you try to run a systemctl command it fails with the following message:

`System has not been booted with systemd as init system (PID 1). Can't operate.`

**Comment by Carazyda** [comment]
Hello @N3tFX Please try add a new mount to community server container
`-v /sys/fs/cgroup:/sys/fs/cgroup:ro`

In close time we will update a github instructions.

**Comment by N3tFX** [comment]
I've just tried it. It doesn't wont to start.

**Comment by aaronouthier** [comment]
See issue #104 
I’ve already discussed this, as well as the solution.

**Comment by N3tFX** [comment]
Thank you **aaronouthier**,

I tried adding also the "**-v /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd:ro**", hopping that this would be the last missing piece of the puzzle, but no. It didn't work. I didn't try the mounting stuff because I don't want to mess with such important settings on my system. For now, I will wait for the new instructions **Carazyda** said that they will come soon.

One thing I've noticed is that if you are quick and try to access the Commynity server page while the docker is starting, the loading page: **_The portal start up process might take some time, please wait..._** is loading. But after the docker finish the startup process it goes down again. This means that the server is starting (briefly) but then shuts down.

I just can't understand it though. I've had no problem with the Document server for so long, both running the docker AND updating the docker. Also the Community server was installing fine up untill the version: **9.6.5.771**.

**Comment by aaronouthier** [comment]
I understand your concern about not wanting to hose your system. As for the “mounting stuff”. I’m not 100% certain that it is needed. Indeed, I have shutdown my system without stopping the container, and when I started my system up again, the containers were relaunched without mounting those folders, and it DID work. My worry is that those folders are intended to have a temporary filesystem (that’s what TMPFS means). On Windows, you’d call it a RAM disk. The idea is that it’s contents are wiped between reboots. There isn’t anything important in them, it’s basically “scratch paper”. It might or might not work without mount the tmpfs. If you want to try it without mounting, run ‘mkdir -p ./run/lock’ and then omit the second mount in the docker command line for ‘-v ./lock:’ . I don’t recall what I put after the colon at the end of that line, but either way, you can omit it if you aren’t going to mount the tmpfs’s.

As for the community portal saying “please wait...” this is normal. It happens when the community server first starts up, and waits for the document server to start and be ready. The trouble is that a major change was made to the community server that affects docker users. The trouble is related to systemd - it works fine outside of docker, but comes to a grinding halt if used within docker. When you use document server standalone, you access it directly. When you use it alongside community server, you actually access the document server (and mail server) by proxy through community server.

I propose that you go back to your last known working version of community server, and BACK UP all important data. I started with a fresh install, so I had no data to lose. I did end up wiping all of my docker data several times during the troubleshooting process. Probably not needed for you, but it’s possible.

**Comment by sasha986** [comment]
I have fixed that issue by adding two additional lines in `docker-compose.yml`, example with missing code is below

```
onlyoffice-community-server: 
    privileged: true
    ....
    volumes:
        - ....
        - /sys/fs/cgroup:/sys/fs/cgroup
    ....
```

hopefully this will help to someone!

**Comment by N3tFX** [comment]
If the privileged flag ends up to be necessary to run Docker-CommunityServer, then that's a no go for me. Everywhere I read about the privileged flag, everyone is saying how bad idea it is to run docker containers with privileged flag on.

**Comment by N3tFX** [comment]
I am closing this issue because newer versions have already came out.
