### ISSUE TITLE
slow response from private network

### ISSUE THREAD

**Issue by kong156** [ONLYOFFICE/Docker-CommunityServer#5]
Hi,

I have an annoying behavior for a community server 8.5, docker setup. As long as i keep this instance connected to the internet, everything is going smoothly. After the server is no longer connected to the internet, all apps begin to respond slowly, about 10 seconds between choosing to change the context (seems to be a timeout), from 'documents' section to 'mail' section, for example. During the installation I'm using a public ip address for the host server and when I disconnect i'm using a private class of ip addresses.

**Comment by kong156** [comment]
Looking more carefully I realised that the browser is waiting for responses to some opened tcp connections with other external sites. Is there any way fix this?

**Comment by Dean13** [comment]
Sorry for the delay of the reply.

The issue is in Docker. Please use m,y instruction below to fix it.

Docker specifies Google DNS servers by default. If your server is not going to have access to the Internet, we recommend that you change the default Docker DNS address to the address of your local DNS server. To do that go to the /etc/default/docker file and change the IP address in the following line to the IP address of a DNS server in your local network:

`docker_OPTS="--dns 8.8.8.8"
`

After it please open the files /var/www/onlyoffice/WebStudio/web.appsettings.config and specify if there is a parameter <add key="web.help-center" ?

**Comment by youwoxinqinghao** [comment]
I ran into the same issue as you—there’s a 10-second delay when there’s no network connection. Has it been resolved now?
